In [2]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
X = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
y = raw_df.values[1::2, 2]

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
C:\Users\michael\AppData\Local\Temp\ipykernel_2656\3358670259.py:5: SyntaxWarning: invalid escape sequence '\s'
  raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)


In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [4]:
multiple_linear_model=LinearRegression()

In [5]:
def get_linear_model(X,y):
    ml_model =LinearRegression()
    X_train,X_test,y_train,y_test=train_test_split(X,y)
    ml_model.fit(X_train,y_train)
    y_pred=ml_model.predict(X_test)
    score = r2_score(y_test,y_pred)
    mse=mean_squared_error(y_test,y_pred)
    print(f"Score: {score*100}\nMSE: {mse}")
    print(ml_model.coef_)
    print(ml_model.intercept_)

In [8]:
X_crim_zn_indus=X[:,[0,1,2]]
get_linear_model(X_crim_zn_indus,y)

Score: 22.97181406358669
MSE: 68.96001237467058
[-0.23710925  0.0713592  -0.39652387]
27.05279534142163


In [9]:
X_crim_zn_indus_chas=X[:,[0,1,2,3]]
get_linear_model(X_crim_zn_indus_chas,y)

Score: 33.33382471894608
MSE: 50.034009036154536
[-0.22453363  0.06088022 -0.42615034  6.53140286]
26.926468734324672


In [10]:
X_crim_zn_indus_chas_nox=X[:,[0,1,2,3,4]]
get_linear_model(X_crim_zn_indus_chas_nox,y)

Score: 41.28552257698806
MSE: 54.9046581050944
[-0.19771389  0.0497411  -0.32384078  8.23059618 -5.65677722]
28.724537521268044


In [11]:
X_crim_zn_indus_chas_nox_rm=X[:,[0,1,2,3,4,5]]
get_linear_model(X_crim_zn_indus_chas_nox_rm,y)

Score: 48.03397771045182
MSE: 58.85034006100712
[-0.17162773  0.0164385  -0.19736733  2.48663207 -5.53203678  7.47438021]
-19.041636722208736


In [12]:
X_crim_zn_indus_chas_nox_rm_age=X[:,[0,1,2,3,4,5,6]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age,y)

Score: 56.18619582247977
MSE: 36.930012554844
[-0.1841983   0.01256167 -0.15237414  5.38536256 -1.84428474  7.56197065
 -0.02441272]
-20.375467539242354


In [13]:
X_crim_zn_indus_chas_nox_rm_age_dis=X[:,[0,1,2,3,4,5,6,7]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis,y)

Score: 51.133444212298926
MSE: 44.40770147024779
[ -0.21510931   0.06275601  -0.25483251   3.94754823 -12.52801483
   6.7443927   -0.06086073  -2.01646752]
1.63845050490146


In [14]:
X_crim_zn_indus_chas_nox_rm_age_dis_rad=X[:,[0,1,2,3,4,5,6,7,8,]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis_rad,y)

Score: 73.27717892612074
MSE: 24.852237847344416
[ -0.19716586   0.07196107  -0.13427939   5.30811452 -13.07001225
   6.53469223  -0.05907521  -1.69105413  -0.06352431]
0.853141028923627


In [15]:
X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax=X[:,[0,1,2,3,4,5,6,7,8,9]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax,y)

Score: 55.84252245101333
MSE: 39.79489398436814
[-1.60824804e-01  6.97286692e-02 -9.61431909e-02  5.12163155e+00
 -1.40737183e+01  6.89635955e+00 -4.11542861e-02 -1.59864440e+00
  1.40220795e-01 -1.39493246e-02]
0.7268561773283295


In [16]:
X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio=X[:,[0,1,2,3,4,5,6,7,8,9,10]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio,y)

Score: 69.17009380598755
MSE: 23.427517840289397
[-2.19841753e-01  4.77240308e-02 -7.17173268e-02  2.44242211e+00
 -2.45535114e+01  5.54485594e+00 -4.23375757e-02 -1.82305417e+00
  3.16070231e-01 -1.36929388e-02 -1.07925520e+00]
34.49362108178034


In [17]:
X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio_b=X[:,[0,1,2,3,4,5,6,7,8,9,10,11]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio_b,y)

Score: 63.638865319529515
MSE: 29.43029391402437
[-1.55957561e-01  3.51579666e-02 -1.26483712e-02  3.20376419e+00
 -2.40611354e+01  6.38896264e+00 -3.53966544e-02 -1.49455309e+00
  2.99521776e-01 -1.23237417e-02 -1.00721673e+00  1.17362335e-02]
20.591644135865398


In [18]:
X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio_b_lstat=X[:,[0,1,2,3,4,5,6,7,8,9,10,11,12]]
get_linear_model(X_crim_zn_indus_chas_nox_rm_age_dis_rad_tax_pitratio_b_lstat,y)

Score: 74.08154237898027
MSE: 25.940577575936025
[-1.14239119e-01  4.39984080e-02 -4.86192617e-02  3.00082398e+00
 -1.85266112e+01  3.16826373e+00  1.03549138e-02 -1.55726211e+00
  2.83954081e-01 -9.55415855e-03 -9.07451125e-01  7.84121602e-03
 -5.81284132e-01]
40.8374455243423
